### PR TITLE
[Bug, Feature, Infra]: Refactor table data model, improve data display for most data types

### LINKED ISSUE #117: [Bug]: Issues with null values displaying at a data preview
## Bug Description
For CSV files there are visual issues with null values displaying  at data preview and query result: 
1. For fields with type "number" null values appear as `ERROR: Can't display value`
2. For fields with type "string" null values appear as empty cell
3. For fields with type "date" null values appear as `1/1/1970`

Filter "IS NULL" works for each case. 
I consider `;` as a null value for CSV files
I do not check it on a SQL tables by the way, it may have the same issue

## Steps To Reproduce
1. Upload csv file with few empty values to PondPilot
2. Click to the file to open it
3. See error :)

## Expected Behavior
The `NULL` value appears at cells without values.

## Actual Behavior
1. For fields with type "number" null values appear as `ERROR: Can't display value`
2. For fields with type "string" null values appear as empty cell
3. For fields with type "date" null values appear as `1/1/1970`

## Environment
- Browser: Chrome Version 135.0.7049.96 (Official Build) (32-bit)
- OS: Windows 10 Pro 22H2 19045.5737
- How did you access PondPilot: app.pondpilot.io

### Screenshots
CSV file:

Image

[pondpilot_test.csv](https://github.com/user-attachments/files/19903494/pondpilot_test.csv)

PondPilot GUI:

Image

### PR DESCRIPTION
**Pull request by booandrew**
## Description

- ID generation has been added for columns. The identifiers are used to ensure correct column width adjustment.

- The data model for the table has been changed from `Record<string, any>[]` to `Record<DBColumnId, any>[]`, and values are now retrieved by unique column id instead of non0-unique name. This change allows fixing the bug related to displaying columns with duplicate names.

- A common function has been added to format table data into TSV and CSV formats.

- New tests have been added to copy values from the table.

- Multiple fixes and improvements to how we format data, now mostly matching DuckDB CLI where it is possible and makes sense

Closes #117

## Checklist

- [x] I have added at least one test for the new feature or fixed bug, or this PR does not include any app code changes.
- [x] I have tested the new version using the auto-generated preview URL.

<details>
  <summary>How to Find the Preview URL</summary>

  The app will be deployed to a preview URL automatically every time you push a commit to this PR.

  You can find the preview link in the "Deployments" section at the bottom of this PR:
  - Look for the section with the 🚀 rocket icon that says "This branch was successfully deployed."
  - Alternatively, look for "github-actions bot deployed to preview" in the timeline.
  - Click "View deployment" to open the preview URL.
</details>

### CODE REVIEW

**Comment by mishamsk** [comment]
TODO:
* add new tests
* add deduplication of columns when we create result set for the table (in data-view) and emit a warning notification if there are columns that were removed as duplicates by name

File: src/features/tab-view/components/data-view.tsx [hunk 1]
```diff
@@ -233,59 +211,8 @@ export const DataView = ({ active, dataAdapter, tabId, tabType }: DataViewProps)
...
-          id: notificationId,
-          title: 'Failed to copy selected columns to clipboard',
-          message,
-          loading: false,
-          autoClose: 5000,
-          color: 'red',
-        });
-      }
+    (selectedCols: DBColumn[]) => {
+      return copySelectedColumns(selectedCols, dataAdapter);
```
Comment (mishamsk) [inline src/features/tab-view/components/data-view.tsx:215]: what do you think about making `copySelectedColumns` API tighther and passing only the `dataAdapter.getAllTableData` in instead of the entire dataAdapter? This way it will be clear without looking into the function that effect dependency array is correct, while currently checking whether we haven't forgotten anything would involve reading the function text

File: src/features/tab-view/hooks/use-table-export.tsx [hunk 2]
```diff
@@ -24,7 +24,17 @@ export const useTableExport = (dataAdapter: DataAdapterApi, tabId: TabId) => {
...
       const headers = columns.map((col) => col.name).join('\t');
-      const rows = data.map((row) => columns.map((col) => row[col.name] ?? '').join('\t'));
+      const rows = data.map((row) =>
+        columns
+          .map((col) => {
+            const value = stringifyTypedValue({
+              value: row[col.name],
+              type: col.sqlType || 'other',
+            });
+            return value ?? '';
```
Comment (mishamsk) [inline src/features/tab-view/hooks/use-table-export.tsx:34]: same, why fallback here?

Comment (mishamsk) [reply src/features/tab-view/hooks/use-table-export.tsx:34]: I think what can really go wrong is if our schema (`columns`) doesn't match what the row has. But then `row[col.name]` will fail, but not value. We should probably first get the column value from the row, and if the column is missing, we should store that data and schema do not match and emit a warning notification, but avoid including any empty strings in the output

Comment (mishamsk) [reply src/features/tab-view/hooks/use-table-export.tsx:34]: Also, `exportTableToCSV` below uses another approach to iterate and handle errors, although it does the same thing and only the format differs really (tabs vs commas with csv-esscaping). How about extracting all three (two here and `copySelectedColumns`) similar things into one utility function that create a list of rows (list of formatted values) + returns any columns that are a mismatch between row-data and schema. Then use the returned result to apply different output formatting (tab delimited, csv)?

PS. I have a hunch that eventually, the easiest way to export in all formats, would be to just run duckdb `copy ... to someBuffer` SQL command and just use that buffer... but that will come later

File: src/components/table/hooks/use-table-selection.tsx
Comment (mishamsk) [inline src/components/table/hooks/use-table-selection.tsx:1]: there is a bug in `handleCopySelectedRows` now (can't comment on the bug line, GitHub won't let me). When you copy rows it would use column ids as headers which are not column names now

Comment (mishamsk) [reply src/components/table/hooks/use-table-selection.tsx:1]: Ok, more bugs:

* Column copy doesn't work for me at all (testing deployed version). Neither one, nor multiple react on `Cmd-C`
* `Cmd-click` works to select multiple columns, but not `Shift-Click` (to select range)

File: src/features/tab-view/hooks/use-table-export.tsx
Comment (mishamsk) [inline src/features/tab-view/hooks/use-table-export.tsx:1]: Copy table doesn't work. Copies empty rows, not even a header...didn't test CSV, but suggest testing.

File: src/utils/table.ts
Comment (mishamsk) [inline src/utils/table.ts:1]: NIT: I think this should be part of db.ts really, as this is used to essentially populate DBColumn model and its downstream usage. `Table` can also be confused with the table component.

File: src/features/tab-view/components/data-view.tsx [hunk 3]
```diff
@@ -56,6 +55,32 @@ export const DataView = ({ active, dataAdapter, tabId, tabType }: DataViewProps)
...
+        title: 'Duplicate columns detected',
+        message: `The following columns are duplicated: ${Array.from(duplicates).join(', ')}`,
+        autoClose: false,
+      });
+    }
+
+    return filteredSchema;
+    // Recalculate it only when the schema changes
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [JSON.stringify(dataAdapter.currentSchema.map((col) => col.name))]);
```
Comment (mishamsk) [inline src/features/tab-view/components/data-view.tsx:82]: I was concerned that we do deduplication here, so I started thinking about this more. And I think we did a mistake when we discussed this. DuckDB does NOT coalesce same named column. It returns both of them:
CleanShot 2025-04-28 at 13 41 34@2x

The idea that the schema has duplicates but result data doesn't also makes no sense if you look at how we get the schema in the first place. We take schema from the arrow reader...so the schema literally comes from actual data and can't really differ from the columns in the data.

So this needs to be reverted and removed and instead visualization logic needs fixing, it should rely on column indexes rather than names everywhere (in copy, export and in table display).

**Review by mishamsk — CHANGES_REQUESTED** [review]
Unfortunately there are a lot of comments and many/most copy realted features are broken by the changes here.

Hence, let's make sure we include a test for each copy/export feature as part of this PR:
- Copy cell to clipboard
- Copy one or more rows to clipboard (including checking that multi-select with cmd/shift works)
- Copy one or more columns to clipboard (including checking that multi-select with cmd/shift works)
- Copy entire table to clipboard
- Export table to csv (I think we already have this one)

File: src/features/tab-view/components/data-view.tsx [hunk 4]
```diff
@@ -298,14 +225,60 @@ export const DataView = ({ active, dataAdapter, tabId, tabType }: DataViewProps)
...
-    // eslint-disable-next-line react-hooks/rules-of-hooks
-    handleOnJumpToRow = useCallback(
-      (rowNumber: number) => setAndCacheDataPage(Math.floor(rowNumber / MAX_DATA_VIEW_PAGE_SIZE)),
-      [],
-    );
-  }
+  const handleOnJumpToRow = useCallback(
+    (rowNumber: number) => setAndCacheDataPage(Math.floor(rowNumber / MAX_DATA_VIEW_PAGE_SIZE)),
+    [setAndCacheDataPage],
+  );
```
[the remark this answers is not in the document]
Comment (mishamsk) [reply src/features/tab-view/components/data-view.tsx:204]: > I chose to follow the rule of not calling hooks conditionally

I'd argue that `if (import.meta.env.DEV)` is not a conditional hook call, since it is known to be static. But

> avoid future changes that might add new conditions in the IF here

this is fair. We would need to either write a long comment above the condition to explain why and what not to do, or remove the condition like you did.

Closing this thread

File: src/features/tab-view/utils.ts [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+/**
+ * Handle copy selected columns
+ */
+export const copyTableColumns = async ({ columns, dataAdapter }: CopyTableColumnsProps) => {
+  // We do not want to call API if no columns are selected
+  if (!columns.length) {
+    return;
+  }
+
+  dataAdapter.currentSchema;
```
Comment (mishamsk) [inline src/features/tab-view/utils.ts:22]: this should go

File: src/utils/arrow.ts [hunk 6]
```diff
@@ -1,31 +1,35 @@
...
 import { DataType } from 'apache-arrow';
+import { getTableColumnId } from './db';
 
 /**
  * Returns an Apache Arrow table as an array of row records.
  */
 export function convertArrowTable(table: Table | RecordBatch): DataTable {
-  return table.toArray().map((row) => row.toJSON());
+  const columns = Array(table.numCols)
+    .fill(0)
```
Comment (mishamsk) [inline src/utils/arrow.ts:11]:
```suggestion
    .fill(null)
```

File: src/utils/arrow.ts [hunk 7]
```diff
@@ -1,31 +1,35 @@
...
+    .map((_, colIndex) => table.getChildAt(colIndex));
+
+  return Array(table.numRows)
+    .fill(0)
```
Comment (mishamsk) [inline src/utils/arrow.ts:15]:
```suggestion
    .fill(null)
```

File: src/utils/db.ts [hunk 8]
```diff
@@ -65,7 +70,10 @@ export const stringifyTypedValue = ({
       }
       case 'integer':
       case 'number': {
-        return formatNumber(value as number);
+        if (typeof value === 'number' || typeof value === 'bigint') {
+          return formatNumber(value);
+        }
+        return '';
```
[the remark this answers is not in the document]
Comment (mishamsk) [reply src/utils/db.ts:77]: up!

File: src/utils/table.ts [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+ *
+ * @param {Record<string, any>[]} data - Array of data objects with key-value pairs
+ * @param {DBColumn[]} columns - Database column definitions
+ * @returns {string[][]} Array of formatted row values
+ */
+export const getStringifyTypedRows = (data: DataTable, columns: DBColumn[]): FormattedRow[] =>
+  data.map((row) =>
+    columns.map((col) =>
+      stringifyTypedValue({
+        value: row[col.columnIndex],
```
Comment (mishamsk) [inline src/utils/table.ts:18]: unsafe, but well, I guess ok for this PR. We'll make it more robust when we hit bugs here, and we will hit them 100% ;-)

File: src/components/table/hooks/use-table-selection.tsx [hunk 10]
```diff
@@ -62,30 +62,18 @@ export const useTableSelection = ({
...
+          .map((cell) => {
+            const { type } = cell.column.columnDef.meta as ColumnMeta;
+            return stringifyTypedValue({ type, value: cell.getValue() });
+          })
+          .join('\t');
+      });
 
-      const csvContent = `${headers}\n${selectedRowsData}`;
-      navigator.clipboard.writeText(csvContent);
+      navigator.clipboard.writeText(tableData.join('\n'));
```
Comment (mishamsk) [inline src/components/table/hooks/use-table-selection.tsx:76]: A couple of thoughts here:

- We dropped column headers from export. I actually think that this a better default behavior, but it is a change, so we need to highlight this at least in a PR description. Better ask our product team to give precise design for the format and behavior of export. E.g. I'd use `Alt/Opt` to toggle whether header is exported or not
- We re-create the copy/export logic instead of using the helpers. This hook has the schema, so why can't it take a subset of table data and pass it to the same `exportTableColumnsToCSV` (with header) and `formatTableDataAsTSV` without headers?

The added benefit of doing the latter is that our TSV is probably really not entirely correct, we do not quote `\t` when exporting => we'll probably need to fix it in a later PR anyway. Re-using the logic will ensure it is fixed everywhere

**Review by mishamsk — CHANGES_REQUESTED** [review]
additional comments. The older one rgd test coverage stay. Otherwise looks great!

**Review by mishamsk — APPROVED** [review]
