### PR TITLE
[Bug]: Fix schema syncronization issue after file change

### LINKED ISSUE #118: [Bug]: PondPilot fails to read a data source after schema change without app restart
## Bug Description

Subj

## Steps To Reproduce
1. Add a csv file with 1 column
2. Open it
3. Modify it, by adding a second column
4. Try sorting or re-openeing
5. See error

## Expected Behavior

New data is picked up automatically without error

## Actual Behavior

Data source read error

## Environment
- Browser: Chrome
- OS: macOS
- How did you access PondPilot: app.pondpilot.io

### Screenshots

Image

Image

### Console Errors

```
Failed to create a reader for the data source: Error: Binder Error: Contents of view were altered: types don't match! Expected [VARCHAR], but found [BIGINT, BIGINT, VARCHAR] instead
```

### PR DESCRIPTION
**Pull request by booandrew**
## Description

 When a CSV file schema is modified externally (e.g., adding/removing columns), PondPilot fails
  to read the updated data and throws a DuckDB Binder Error: "Contents of view were altered:
  types don't match!" or similar schema mismatch errors. Users had to refresh the entire
  application to see updated data.

 ### Root Cause

  The syncFiles() function only re-registered file handles when files changed, but did not
  recreate the associated DuckDB views. This left stale view definitions pointing to the old
  schema while the underlying file had a new structure.

## Related Issues

Fixes #118

## Checklist

- [x] I have added at least one test for the new feature or fixed bug, or this PR does not include any app code changes.
- [x] I have tested the new version using the auto-generated preview URL.

<details>
  <summary>How to Find the Preview URL</summary>

  The app will be deployed to a preview URL automatically every time you push a commit to this PR.

  You can find the preview link in the "Deployments" section at the bottom of this PR:
  - Look for the section with the 🚀 rocket icon that says "This branch was successfully deployed."
  - Alternatively, look for "github-actions bot deployed to preview" in the timeline.
  - Click "View deployment" to open the preview URL.
</details>

### CODE REVIEW

File: src/features/tab-view/hooks/use-data-adapter.ts [hunk 1]
```diff
@@ -423,6 +423,20 @@ export const useDataAdapter = ({ tab, sourceVersion }: UseDataAdapterProps): Dat
             console.error('Data source have been moved or deleted:', error);
             setAppendDataSourceReadError('Data source have been moved or deleted.');
           }
+        } else if (
+          error.message?.includes('Binder Error') ||
```
Comment (melonamin) [inline src/features/tab-view/hooks/use-data-adapter.ts:427]: Extract this to utils function, you have it twice in here.

```typescript
/**
 * WARNING: These error patterns are fragile and depend on DuckDB's specific error messages.
 * If DuckDB changes these messages in future versions, this detection may break.
 * 
 * These patterns are used to detect schema mismatch errors that can be recovered
 * by re-syncing files and recreating views.
 */
const SCHEMA_ERROR_PATTERNS = [
  'Binder Error',
  'does not exist',
  'Invalid column',
  'Contents of view were altered',
];

/**
 * Detects if an error is related to a schema mismatch that can potentially
 * be recovered by re-syncing files and recreating views.
 * 
 * @param error The error to check
 * @returns true if the error appears to be a schema mismatch error
 */
export function isSchemaChangeError(error: unknown): boolean {
  const message = (error as Error)?.message ?? '';
  return SCHEMA_ERROR_PATTERNS.some((pattern) => message.includes(pattern));
}
```
